### ISSUE TITLE
No attribute 'connect setup finished'

### ISSUE THREAD

**Issue by Danish22** [JamesHagerman/Crazyflie_Python_Demos#1]
Hii, I was just trying to make crazyflie 2.0 to fly with custom code. Saw yours. Quite simple and easy but am getting error in running your code.
it says 
AttributeError: Crazyflie instance has no attribute 'conncetSetupFinished' 

Also I would appreciate that if you tell me how to resolve that Bad libusb error you mentioned in the comment. I guess I am facing that error too.

**Comment by devdinu** [comment]
Hi, probably you can try `crazyflie.connected.add_callback(self.callback_method)` instead of `connectSetupFinished`. 

To be precise at line 16 `self.crazyflie.connectSetupFinished.add_callback(self.connectSetupFinished)`
 to `self.crazyflie.connected.add_callback(self.connectSetupFinished)`.

I've tried to control the copter, see whether it helps you [my github : copter-controller](https://github.com/dineshkumar-cse/ElateCopter)

**Comment by Danish22** [comment]
Thank you Dinesh
